# Generated by Django 3.2 on 2022-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
