# Generated by Django 3.2 on 2022-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220510_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(default=12, upload_to='images/prod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
